name: Publish
on:
  release:
    types: [created]

jobs:

  publish-docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Upload to Docker
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jib -Pdocker=drpcorg -Pbuild_version=${{ github.ref_name }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build zip
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distZip -Pbuild_version=${{ github.ref_name }}
      - name: Upload Release
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./build/distributions/*.zip
          file_glob: true
