name: Tests

on:
  # if pushed directly
  push:
    paths-ignore:
      - '**/docs/**'
      - '**/.github/**'
    branches:
      - master
      - release/*
      - ci/*
  # on a pull request
  pull_request:
    paths-ignore:
      - '**/docs/**'
    branches:
      - master
      - release/*
      - ci/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20

      - name: Install System Libs
        run: sudo apt-get install -y openssl libapr1
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check
        run: make test
        env:
          CI: true
